@Rackets_HostAddress = http://localhost:5202

### Get all rackets

GET {{Rackets_HostAddress}}/Rackets
Accept: application/json

### OpenAPI

GET {{Rackets_HostAddress}}/scalar/v1
Accept: application/json